# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_test.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'proto_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto_test.proto\x12\x06\x61makna\"\x9d\x01\n\x0bMainMessage\x12\"\n\x07request\x18\x01 \x01(\x0b\x32\x0f.amakna.RequestH\x00\x12$\n\x08response\x18\x02 \x01(\x0b\x32\x10.amakna.ResponseH\x00\x12\x39\n\x05\x65vent\x18\x03 \x01(\x0b\x32(.amakna.MapComplementaryInformationEventH\x00\x42\t\n\x07\x63ontent\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"B\n\x05\x45vent\x12\x39\n\x07\x63ontent\x18\x01 \x01(\x0b\x32(.amakna.MapComplementaryInformationEvent\"v\n MapComplementaryInformationEvent\x12\x11\n\tsubareaId\x18\x01 \x01(\r\x12\r\n\x05mapId\x18\x02 \x01(\x04\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x1d\n\x06houses\x18\x04 \x03(\x0b\x32\r.amakna.House\")\n\x05House\x12\x0f\n\x07houseId\x18\x01 \x01(\r\x12\x0f\n\x07modelId\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAINMESSAGE']._serialized_start=29
  _globals['_MAINMESSAGE']._serialized_end=186
  _globals['_REQUEST']._serialized_start=188
  _globals['_REQUEST']._serialized_end=209
  _globals['_RESPONSE']._serialized_start=211
  _globals['_RESPONSE']._serialized_end=237
  _globals['_EVENT']._serialized_start=239
  _globals['_EVENT']._serialized_end=305
  _globals['_MAPCOMPLEMENTARYINFORMATIONEVENT']._serialized_start=307
  _globals['_MAPCOMPLEMENTARYINFORMATIONEVENT']._serialized_end=425
  _globals['_HOUSE']._serialized_start=427
  _globals['_HOUSE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
