# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufer/proto_test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotobufer/proto_test.proto\x12\x06\x61makna\"\x9d\x01\n\x0bMainMessage\x12\"\n\x07request\x18\x01 \x01(\x0b\x32\x0f.amakna.RequestH\x00\x12$\n\x08response\x18\x02 \x01(\x0b\x32\x10.amakna.ResponseH\x00\x12\x39\n\x05\x65vent\x18\x03 \x01(\x0b\x32(.amakna.MapComplementaryInformationEventH\x00\x42\t\n\x07\x63ontent\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"B\n\x05\x45vent\x12\x39\n\x07\x63ontent\x18\x01 \x01(\x0b\x32(.amakna.MapComplementaryInformationEvent\"c\n MapComplementaryInformationEvent\x12\x11\n\tsubareaId\x18\x01 \x01(\r\x12\r\n\x05mapId\x18\x02 \x01(\x04\x12\x1d\n\x15hasAggressiveMonsters\x18\t \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufer.proto_test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINMESSAGE._serialized_start=40
  _MAINMESSAGE._serialized_end=197
  _REQUEST._serialized_start=199
  _REQUEST._serialized_end=220
  _RESPONSE._serialized_start=222
  _RESPONSE._serialized_end=248
  _EVENT._serialized_start=250
  _EVENT._serialized_end=316
  _MAPCOMPLEMENTARYINFORMATIONEVENT._serialized_start=318
  _MAPCOMPLEMENTARYINFORMATIONEVENT._serialized_end=417
# @@protoc_insertion_point(module_scope)
